/*****Omni NXT Bot*****/
/*     Ryan Bahm      */
/*     11/19/2010     */
/**********************/

#pragma config(Sensor, S1,     Touch,               sensorTouch)
#pragma config(Sensor, S2,     Sound,               sensorSoundDB)
#pragma config(Sensor, S3,     Light,               sensorLightActive)
#pragma config(Sensor, S4,     Sonar,               sensorSONAR)
#pragma config(Motor,  motorA,          A,             tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          B,             tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Variables Global
int Run = 1;
//Movement-------
int SpeedA = 0;
int SpeedB = 0;
int SpeedC = 0;

int Direction = 0;
int StopMove = 1;

int Spin = 0;

int MaxSpeed = 50;
//------------------
//Light Variables

int LightSet;
int DarkSet;
int Grey;
int waitT;






void Revolve()
{
  motor[A] = 100;
  motor[B] = 100;
  motor[C] = 100;

}

void setup()
{
  while (waitT < 3)
  {
    PlaySound(soundBlip);
    wait1Msec(1000);
    waitT ++;
  }
  wait1Msec(1000);
  waitT = 0;
  PlaySound(soundLowBuzz);
  wait1Msec(1000);
  LightSet = SensorValue[Light];
  while (waitT < 3)
  {
    PlaySound(soundBlip);
    wait1Msec(1000);
    waitT ++;
  }
  waitT = 0;
  DarkSet = SensorValue[Light];

  Grey = (DarkSet +LightSet)/2;



}


void MoveBot()
{
  if (SensorValue[Light]



}





task MotorControl()
{
  while (Run ==1)
  {
    SpeedA =  (MaxSpeed-abs(Spin))*cosDegrees(Direction-150)*StopMove;
    SpeedB =  (MaxSpeed-abs(Spin))*cosDegrees(Direction+90)*StopMove;
    SpeedC =  (MaxSpeed-abs(Spin))*cosDegrees(Direction-30)*StopMove;


    SpeedA = SpeedA+Spin;
    SpeedB = SpeedB+Spin;
    SpeedC = SpeedC+Spin;

    motor[A] = SpeedA;
    motor[B] = SpeedB;
    motor[C] = SpeedC;

    if (SensorValue[Touch] ==1)
    {
      Run =0;
    }
  }


}



task main()
{
  setup();


  StartTask(MotorControl);

  while(Run==1)
  {

    MoveBot();


  }


}
